# Generated by Django 3.1 on 2021-01-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pics',
            field=models.ImageField(default='default.jpeg', upload_to=''),
        ),
    ]
