# Generated by Django 3.1 on 2021-01-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_profile_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'django'), (2, 'kakao')], default=1),
        ),
    ]
