# Generated by Django 3.1 on 2021-01-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210113_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pics',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
