# Generated by Django 3.1 on 2021-01-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210113_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'django'), (2, 'kakao')], default=1),
        ),
    ]
