# Generated by Django 3.1 on 2021-01-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210113_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pics',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
