# Generated by Django 3.1 on 2021-01-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210114_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pics',
            field=models.ImageField(default='/static/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'django'), (2, 'kakao')], default=1),
        ),
    ]
