# Generated by Django 3.1 on 2021-01-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210115_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'django'), (2, 'kakao')], default=1, null=True),
        ),
    ]
