# Generated by Django 3.1 on 2021-01-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210115_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pics',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
